_BASE_: "Base-DefGird-MRCNN-FPN.yaml"
MODEL:
  WEIGHTS: init_weights/mrcnn_r50_1x.pkl
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res3, Res4, Res5
    DEFORM_MODULATED: False
  DEFGRID_MASK_HEAD:
    W_AREA: 0.05
    W_LAPLACIAN: 0.05
INPUT:
  MIN_SIZE_TRAIN: (800,)
DATASETS:
  TRAIN: ("indiscapes_train_val_combined",)
  TEST: ("indiscapes_test",)
OUTPUT_DIR: "outputs/Palmira"
